FROM ubuntu:18.04

RUN apt-get update && apt-get install -y

RUN apt install nodejs npm python3 python3-pip -y

RUN npm install franc-cli --global

RUN mkdir -p /src

WORKDIR /src

ADD app.py /src/app.py
ADD requirements.txt /src/requirements.txt


RUN pip3 install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python3"]

CMD ["app.py"]
